// <auto-generated />
using System;
using GridTrack.Infrastructure.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GridTrack.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260608135408_AddAnomalyTypeToDeliveries")]
    partial class AddAnomalyTypeToDeliveries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GridTrack.Domain.Deliveries.Delivery", b =>
                {
                    b.Property<Guid>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualEta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("AnomalyFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("AnomalyReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("AnomalyTypeValue")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AssignedDriverId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("CurrentLocation")
                        .IsRequired()
                        .HasColumnType("geometry (point)");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DistrictId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ExpectedEta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PickedUpAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("DeliveryId");

                    b.HasIndex("AssignedDriverId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("Status");

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("GridTrack.Domain.Drivers.Driver", b =>
                {
                    b.Property<Guid>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DistrictId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry (point)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("DriverId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("IsActive");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("GridTrack.Domain.H3Districts.H3District", b =>
                {
                    b.Property<string>("H3Index")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Polygon>("BoundaryPolygon")
                        .IsRequired()
                        .HasColumnType("geometry (point)");

                    b.Property<Point>("CenterPoint")
                        .IsRequired()
                        .HasColumnType("geometry (point)");

                    b.Property<int>("Resolution")
                        .HasColumnType("integer");

                    b.HasKey("H3Index");

                    b.HasIndex("Resolution");

                    b.ToTable("H3District");
                });

            modelBuilder.Entity("GridTrack.Infrastructure.Data.DeliveryRoute", b =>
                {
                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision");

                    b.HasKey("DeliveryId", "Sequence");

                    b.HasIndex("DeliveryId");

                    b.ToTable("delivery_routes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
